version: '3.1'

volumes:
  mysql-volume:
  mongo-data:

services:
  ghost:
    image: ghost:3.9.0-alpine
    restart: always
    ports:
      - 2368:2368
    environment:
      # see https://docs.ghost.org/docs/config#section-running-ghost-with-config-env-variables
      database__client: mysql
      database__connection__host: mysql-db
      database__connection__user: ghost-user
      database__connection__password: supersecret
      database__connection__database: db
      url: http://78.46.199.56
    volumes:
      - /var/ghost/content/:/var/lib/ghost/content/
    depends_on:
      - mysql-db
    links:
      - express:expre.ss

  mysql-db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: ghost-user
      MYSQL_PASSWORD: supersecret
      MYSQL_DATABASE: db
    volumes:
      - mysql-volume:/var/lib/mysql

  # This service is extended
  # automatically by docker-compose.override.yml (in development)
  # or explicitly by docker-compose-prod.yml (in production)
  express:
    restart: always
    env_file: .env
    ports:
      - "3000:3000"
    volumes:
      - /var/firebase-auth/:/var/firebase-auth
    links:
      - mongo-db
    depends_on: 
      - mongo-db

  mongo-db:
    image: 'mongo:4.2.3'
    restart: always
    environment:
        - MONGO_INITDB_DATABASE=fffapp
        - MONGO_INITDB_ROOT_USERNAME=root
        - MONGO_INITDB_ROOT_PASSWORD=root
    volumes:
        - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
        - mongo-data:/data/db
    ports:
        - '27017-27019:27017-27019'
