# This file needs to be included explicitly by calling
# docker-compose -f docker-compose.yml -f docker-compose-prod.yml up
version: '3.1'

services:
  express:
    image: express:prod
    build:
      context: .
      dockerfile: Dockerfile-prod
