version: '3.1'

services:
  express:
    container_name: express-main-module
    restart: always
    image: express:prod
    build:
      context: .
      dockerfile: Dockerfile-prod
    env_file: .env
    command: node dist/server.js
    ports:
      - "3000:3000"
    links:
      - mongo-db
