FROM node:10-alpine

# Specify working directory
WORKDIR /usr/src/app

# Copy package.json AND package-lock.json
COPY package*.json ./

# Install npm dependencies (without dev-dependencies)
RUN npm ci --only=production

# Copy files to working directory
COPY . .

# Compile ts to js
RUN npm run build

EXPOSE 3000

CMD [ "node", "dist/app.js" ]
