name: Mark stale issues and pull requests

on:
  schedule:
  - cron: "0 0 * * *"

jobs:
  stale:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/stale@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        stale-issue-message: 'This issue seems to be stale...'
        stale-pr-message: 'This PR seems to be stale...'
        stale-issue-label: 'no-activity'
        stale-pr-label: 'no-activity'
